version: "3"
services:
  database:
    container_name: divide-ai
    image: postgres
    restart: always
    environment:
      POSTGRES_DATABASE_LOCAL: divide-ai
      POSTGRES_DB: divide-ai
      POSTGRES_HOST_LOCAL: 0.0.0.0
      POSTGRES_PASSWORD_LOCAL: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT_LOCAL: 5432
      POSTGRES_USER_LOCAL: postgres
    ports:
      - "5432:5432"
    networks:
      - network
networks:
  network:
    driver: bridge
